// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: api/proto/shellsync.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_api_proto_shellsync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shellsync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_shellsync_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

type CreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	FrontendUrl   string                 `protobuf:"bytes,2,opt,name=frontend_url,json=frontendUrl,proto3" json:"frontend_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_api_proto_shellsync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shellsync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_shellsync_proto_rawDescGZIP(), []int{1}
}

func (x *CreateResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CreateResponse) GetFrontendUrl() string {
	if x != nil {
		return x.FrontendUrl
	}
	return ""
}

type ClientUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ClientUpdate_InitialMessage
	//	*ClientUpdate_PtyOutput
	Payload       isClientUpdate_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientUpdate) Reset() {
	*x = ClientUpdate{}
	mi := &file_api_proto_shellsync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientUpdate) ProtoMessage() {}

func (x *ClientUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shellsync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientUpdate.ProtoReflect.Descriptor instead.
func (*ClientUpdate) Descriptor() ([]byte, []int) {
	return file_api_proto_shellsync_proto_rawDescGZIP(), []int{2}
}

func (x *ClientUpdate) GetPayload() isClientUpdate_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ClientUpdate) GetInitialMessage() *InitialAgentMessage {
	if x != nil {
		if x, ok := x.Payload.(*ClientUpdate_InitialMessage); ok {
			return x.InitialMessage
		}
	}
	return nil
}

func (x *ClientUpdate) GetPtyOutput() []byte {
	if x != nil {
		if x, ok := x.Payload.(*ClientUpdate_PtyOutput); ok {
			return x.PtyOutput
		}
	}
	return nil
}

type isClientUpdate_Payload interface {
	isClientUpdate_Payload()
}

type ClientUpdate_InitialMessage struct {
	InitialMessage *InitialAgentMessage `protobuf:"bytes,1,opt,name=initial_message,json=initialMessage,proto3,oneof"`
}

type ClientUpdate_PtyOutput struct {
	PtyOutput []byte `protobuf:"bytes,2,opt,name=pty_output,json=ptyOutput,proto3,oneof"`
}

func (*ClientUpdate_InitialMessage) isClientUpdate_Payload() {}

func (*ClientUpdate_PtyOutput) isClientUpdate_Payload() {}

type InitialAgentMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitialAgentMessage) Reset() {
	*x = InitialAgentMessage{}
	mi := &file_api_proto_shellsync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitialAgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitialAgentMessage) ProtoMessage() {}

func (x *InitialAgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shellsync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitialAgentMessage.ProtoReflect.Descriptor instead.
func (*InitialAgentMessage) Descriptor() ([]byte, []int) {
	return file_api_proto_shellsync_proto_rawDescGZIP(), []int{3}
}

func (x *InitialAgentMessage) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ServerUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerUpdate_ServerHello
	//	*ServerUpdate_PtyInput
	Payload       isServerUpdate_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerUpdate) Reset() {
	*x = ServerUpdate{}
	mi := &file_api_proto_shellsync_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerUpdate) ProtoMessage() {}

func (x *ServerUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shellsync_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerUpdate.ProtoReflect.Descriptor instead.
func (*ServerUpdate) Descriptor() ([]byte, []int) {
	return file_api_proto_shellsync_proto_rawDescGZIP(), []int{4}
}

func (x *ServerUpdate) GetPayload() isServerUpdate_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerUpdate) GetServerHello() string {
	if x != nil {
		if x, ok := x.Payload.(*ServerUpdate_ServerHello); ok {
			return x.ServerHello
		}
	}
	return ""
}

func (x *ServerUpdate) GetPtyInput() []byte {
	if x != nil {
		if x, ok := x.Payload.(*ServerUpdate_PtyInput); ok {
			return x.PtyInput
		}
	}
	return nil
}

type isServerUpdate_Payload interface {
	isServerUpdate_Payload()
}

type ServerUpdate_ServerHello struct {
	ServerHello string `protobuf:"bytes,1,opt,name=server_hello,json=serverHello,proto3,oneof"`
}

type ServerUpdate_PtyInput struct {
	PtyInput []byte `protobuf:"bytes,2,opt,name=pty_input,json=ptyInput,proto3,oneof"`
}

func (*ServerUpdate_ServerHello) isServerUpdate_Payload() {}

func (*ServerUpdate_PtyInput) isServerUpdate_Payload() {}

var File_api_proto_shellsync_proto protoreflect.FileDescriptor

const file_api_proto_shellsync_proto_rawDesc = "" +
	"\n" +
	"\x19api/proto/shellsync.proto\x12\tshellsync\"#\n" +
	"\rCreateRequest\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\"R\n" +
	"\x0eCreateResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12!\n" +
	"\ffrontend_url\x18\x02 \x01(\tR\vfrontendUrl\"\x85\x01\n" +
	"\fClientUpdate\x12I\n" +
	"\x0finitial_message\x18\x01 \x01(\v2\x1e.shellsync.InitialAgentMessageH\x00R\x0einitialMessage\x12\x1f\n" +
	"\n" +
	"pty_output\x18\x02 \x01(\fH\x00R\tptyOutputB\t\n" +
	"\apayload\"4\n" +
	"\x13InitialAgentMessage\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"]\n" +
	"\fServerUpdate\x12#\n" +
	"\fserver_hello\x18\x01 \x01(\tH\x00R\vserverHello\x12\x1d\n" +
	"\tpty_input\x18\x02 \x01(\fH\x00R\bptyInputB\t\n" +
	"\apayload2\x91\x01\n" +
	"\tShellSync\x12D\n" +
	"\rCreateSession\x12\x18.shellsync.CreateRequest\x1a\x19.shellsync.CreateResponse\x12>\n" +
	"\x06Stream\x12\x17.shellsync.ClientUpdate\x1a\x17.shellsync.ServerUpdate(\x010\x01B+Z)github.com/Ayush-Vish/shellsync/api/protob\x06proto3"

var (
	file_api_proto_shellsync_proto_rawDescOnce sync.Once
	file_api_proto_shellsync_proto_rawDescData []byte
)

func file_api_proto_shellsync_proto_rawDescGZIP() []byte {
	file_api_proto_shellsync_proto_rawDescOnce.Do(func() {
		file_api_proto_shellsync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_shellsync_proto_rawDesc), len(file_api_proto_shellsync_proto_rawDesc)))
	})
	return file_api_proto_shellsync_proto_rawDescData
}

var file_api_proto_shellsync_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_proto_shellsync_proto_goTypes = []any{
	(*CreateRequest)(nil),       // 0: shellsync.CreateRequest
	(*CreateResponse)(nil),      // 1: shellsync.CreateResponse
	(*ClientUpdate)(nil),        // 2: shellsync.ClientUpdate
	(*InitialAgentMessage)(nil), // 3: shellsync.InitialAgentMessage
	(*ServerUpdate)(nil),        // 4: shellsync.ServerUpdate
}
var file_api_proto_shellsync_proto_depIdxs = []int32{
	3, // 0: shellsync.ClientUpdate.initial_message:type_name -> shellsync.InitialAgentMessage
	0, // 1: shellsync.ShellSync.CreateSession:input_type -> shellsync.CreateRequest
	2, // 2: shellsync.ShellSync.Stream:input_type -> shellsync.ClientUpdate
	1, // 3: shellsync.ShellSync.CreateSession:output_type -> shellsync.CreateResponse
	4, // 4: shellsync.ShellSync.Stream:output_type -> shellsync.ServerUpdate
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_shellsync_proto_init() }
func file_api_proto_shellsync_proto_init() {
	if File_api_proto_shellsync_proto != nil {
		return
	}
	file_api_proto_shellsync_proto_msgTypes[2].OneofWrappers = []any{
		(*ClientUpdate_InitialMessage)(nil),
		(*ClientUpdate_PtyOutput)(nil),
	}
	file_api_proto_shellsync_proto_msgTypes[4].OneofWrappers = []any{
		(*ServerUpdate_ServerHello)(nil),
		(*ServerUpdate_PtyInput)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_shellsync_proto_rawDesc), len(file_api_proto_shellsync_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_shellsync_proto_goTypes,
		DependencyIndexes: file_api_proto_shellsync_proto_depIdxs,
		MessageInfos:      file_api_proto_shellsync_proto_msgTypes,
	}.Build()
	File_api_proto_shellsync_proto = out.File
	file_api_proto_shellsync_proto_goTypes = nil
	file_api_proto_shellsync_proto_depIdxs = nil
}
