// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: api/proto/shellsync.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_api_proto_shellsync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shellsync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_shellsync_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

type CreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	FrontendUrl   string                 `protobuf:"bytes,2,opt,name=frontend_url,json=frontendUrl,proto3" json:"frontend_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_api_proto_shellsync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shellsync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_shellsync_proto_rawDescGZIP(), []int{1}
}

func (x *CreateResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CreateResponse) GetFrontendUrl() string {
	if x != nil {
		return x.FrontendUrl
	}
	return ""
}

// --- Messages from Agent (Client) to Server ---
type ClientUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ClientUpdate_InitialMessage
	//	*ClientUpdate_PtyOutput
	//	*ClientUpdate_TerminalCreatedResponse
	//	*ClientUpdate_TerminalError
	Payload       isClientUpdate_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientUpdate) Reset() {
	*x = ClientUpdate{}
	mi := &file_api_proto_shellsync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientUpdate) ProtoMessage() {}

func (x *ClientUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shellsync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientUpdate.ProtoReflect.Descriptor instead.
func (*ClientUpdate) Descriptor() ([]byte, []int) {
	return file_api_proto_shellsync_proto_rawDescGZIP(), []int{2}
}

func (x *ClientUpdate) GetPayload() isClientUpdate_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ClientUpdate) GetInitialMessage() *InitialAgentMessage {
	if x != nil {
		if x, ok := x.Payload.(*ClientUpdate_InitialMessage); ok {
			return x.InitialMessage
		}
	}
	return nil
}

func (x *ClientUpdate) GetPtyOutput() *TerminalOutput {
	if x != nil {
		if x, ok := x.Payload.(*ClientUpdate_PtyOutput); ok {
			return x.PtyOutput
		}
	}
	return nil
}

func (x *ClientUpdate) GetTerminalCreatedResponse() *TerminalCreatedResponse {
	if x != nil {
		if x, ok := x.Payload.(*ClientUpdate_TerminalCreatedResponse); ok {
			return x.TerminalCreatedResponse
		}
	}
	return nil
}

func (x *ClientUpdate) GetTerminalError() *TerminalError {
	if x != nil {
		if x, ok := x.Payload.(*ClientUpdate_TerminalError); ok {
			return x.TerminalError
		}
	}
	return nil
}

type isClientUpdate_Payload interface {
	isClientUpdate_Payload()
}

type ClientUpdate_InitialMessage struct {
	InitialMessage *InitialAgentMessage `protobuf:"bytes,1,opt,name=initial_message,json=initialMessage,proto3,oneof"`
}

type ClientUpdate_PtyOutput struct {
	PtyOutput *TerminalOutput `protobuf:"bytes,2,opt,name=pty_output,json=ptyOutput,proto3,oneof"`
}

type ClientUpdate_TerminalCreatedResponse struct {
	TerminalCreatedResponse *TerminalCreatedResponse `protobuf:"bytes,3,opt,name=terminal_created_response,json=terminalCreatedResponse,proto3,oneof"` // Agent confirms terminal creation
}

type ClientUpdate_TerminalError struct {
	TerminalError *TerminalError `protobuf:"bytes,4,opt,name=terminal_error,json=terminalError,proto3,oneof"`
}

func (*ClientUpdate_InitialMessage) isClientUpdate_Payload() {}

func (*ClientUpdate_PtyOutput) isClientUpdate_Payload() {}

func (*ClientUpdate_TerminalCreatedResponse) isClientUpdate_Payload() {}

func (*ClientUpdate_TerminalError) isClientUpdate_Payload() {}

type TerminalError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TerminalId    string                 `protobuf:"bytes,1,opt,name=terminal_id,json=terminalId,proto3" json:"terminal_id,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalError) Reset() {
	*x = TerminalError{}
	mi := &file_api_proto_shellsync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalError) ProtoMessage() {}

func (x *TerminalError) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shellsync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalError.ProtoReflect.Descriptor instead.
func (*TerminalError) Descriptor() ([]byte, []int) {
	return file_api_proto_shellsync_proto_rawDescGZIP(), []int{3}
}

func (x *TerminalError) GetTerminalId() string {
	if x != nil {
		return x.TerminalId
	}
	return ""
}

func (x *TerminalError) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type InitialAgentMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitialAgentMessage) Reset() {
	*x = InitialAgentMessage{}
	mi := &file_api_proto_shellsync_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitialAgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitialAgentMessage) ProtoMessage() {}

func (x *InitialAgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shellsync_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitialAgentMessage.ProtoReflect.Descriptor instead.
func (*InitialAgentMessage) Descriptor() ([]byte, []int) {
	return file_api_proto_shellsync_proto_rawDescGZIP(), []int{4}
}

func (x *InitialAgentMessage) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type TerminalOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TerminalId    string                 `protobuf:"bytes,1,opt,name=terminal_id,json=terminalId,proto3" json:"terminal_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalOutput) Reset() {
	*x = TerminalOutput{}
	mi := &file_api_proto_shellsync_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalOutput) ProtoMessage() {}

func (x *TerminalOutput) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shellsync_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalOutput.ProtoReflect.Descriptor instead.
func (*TerminalOutput) Descriptor() ([]byte, []int) {
	return file_api_proto_shellsync_proto_rawDescGZIP(), []int{5}
}

func (x *TerminalOutput) GetTerminalId() string {
	if x != nil {
		return x.TerminalId
	}
	return ""
}

func (x *TerminalOutput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type TerminalCreatedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TerminalId    string                 `protobuf:"bytes,1,opt,name=terminal_id,json=terminalId,proto3" json:"terminal_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalCreatedResponse) Reset() {
	*x = TerminalCreatedResponse{}
	mi := &file_api_proto_shellsync_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalCreatedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalCreatedResponse) ProtoMessage() {}

func (x *TerminalCreatedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shellsync_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalCreatedResponse.ProtoReflect.Descriptor instead.
func (*TerminalCreatedResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_shellsync_proto_rawDescGZIP(), []int{6}
}

func (x *TerminalCreatedResponse) GetTerminalId() string {
	if x != nil {
		return x.TerminalId
	}
	return ""
}

type ServerUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerUpdate_ServerHello
	//	*ServerUpdate_PtyInput
	//	*ServerUpdate_CreateTerminalRequest
	Payload       isServerUpdate_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerUpdate) Reset() {
	*x = ServerUpdate{}
	mi := &file_api_proto_shellsync_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerUpdate) ProtoMessage() {}

func (x *ServerUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shellsync_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerUpdate.ProtoReflect.Descriptor instead.
func (*ServerUpdate) Descriptor() ([]byte, []int) {
	return file_api_proto_shellsync_proto_rawDescGZIP(), []int{7}
}

func (x *ServerUpdate) GetPayload() isServerUpdate_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerUpdate) GetServerHello() string {
	if x != nil {
		if x, ok := x.Payload.(*ServerUpdate_ServerHello); ok {
			return x.ServerHello
		}
	}
	return ""
}

func (x *ServerUpdate) GetPtyInput() *TerminalInput {
	if x != nil {
		if x, ok := x.Payload.(*ServerUpdate_PtyInput); ok {
			return x.PtyInput
		}
	}
	return nil
}

func (x *ServerUpdate) GetCreateTerminalRequest() *CreateTerminalRequest {
	if x != nil {
		if x, ok := x.Payload.(*ServerUpdate_CreateTerminalRequest); ok {
			return x.CreateTerminalRequest
		}
	}
	return nil
}

type isServerUpdate_Payload interface {
	isServerUpdate_Payload()
}

type ServerUpdate_ServerHello struct {
	ServerHello string `protobuf:"bytes,1,opt,name=server_hello,json=serverHello,proto3,oneof"`
}

type ServerUpdate_PtyInput struct {
	PtyInput *TerminalInput `protobuf:"bytes,2,opt,name=pty_input,json=ptyInput,proto3,oneof"`
}

type ServerUpdate_CreateTerminalRequest struct {
	CreateTerminalRequest *CreateTerminalRequest `protobuf:"bytes,3,opt,name=create_terminal_request,json=createTerminalRequest,proto3,oneof"`
}

func (*ServerUpdate_ServerHello) isServerUpdate_Payload() {}

func (*ServerUpdate_PtyInput) isServerUpdate_Payload() {}

func (*ServerUpdate_CreateTerminalRequest) isServerUpdate_Payload() {}

type TerminalInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TerminalId    string                 `protobuf:"bytes,1,opt,name=terminal_id,json=terminalId,proto3" json:"terminal_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalInput) Reset() {
	*x = TerminalInput{}
	mi := &file_api_proto_shellsync_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalInput) ProtoMessage() {}

func (x *TerminalInput) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shellsync_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalInput.ProtoReflect.Descriptor instead.
func (*TerminalInput) Descriptor() ([]byte, []int) {
	return file_api_proto_shellsync_proto_rawDescGZIP(), []int{8}
}

func (x *TerminalInput) GetTerminalId() string {
	if x != nil {
		return x.TerminalId
	}
	return ""
}

func (x *TerminalInput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateTerminalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TerminalId    string                 `protobuf:"bytes,1,opt,name=terminal_id,json=terminalId,proto3" json:"terminal_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTerminalRequest) Reset() {
	*x = CreateTerminalRequest{}
	mi := &file_api_proto_shellsync_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTerminalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTerminalRequest) ProtoMessage() {}

func (x *CreateTerminalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shellsync_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTerminalRequest.ProtoReflect.Descriptor instead.
func (*CreateTerminalRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_shellsync_proto_rawDescGZIP(), []int{9}
}

func (x *CreateTerminalRequest) GetTerminalId() string {
	if x != nil {
		return x.TerminalId
	}
	return ""
}

var File_api_proto_shellsync_proto protoreflect.FileDescriptor

const file_api_proto_shellsync_proto_rawDesc = "" +
	"\n" +
	"\x19api/proto/shellsync.proto\x12\tshellsync\"#\n" +
	"\rCreateRequest\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\"R\n" +
	"\x0eCreateResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12!\n" +
	"\ffrontend_url\x18\x02 \x01(\tR\vfrontendUrl\"\xc5\x02\n" +
	"\fClientUpdate\x12I\n" +
	"\x0finitial_message\x18\x01 \x01(\v2\x1e.shellsync.InitialAgentMessageH\x00R\x0einitialMessage\x12:\n" +
	"\n" +
	"pty_output\x18\x02 \x01(\v2\x19.shellsync.TerminalOutputH\x00R\tptyOutput\x12`\n" +
	"\x19terminal_created_response\x18\x03 \x01(\v2\".shellsync.TerminalCreatedResponseH\x00R\x17terminalCreatedResponse\x12A\n" +
	"\x0eterminal_error\x18\x04 \x01(\v2\x18.shellsync.TerminalErrorH\x00R\rterminalErrorB\t\n" +
	"\apayload\"F\n" +
	"\rTerminalError\x12\x1f\n" +
	"\vterminal_id\x18\x01 \x01(\tR\n" +
	"terminalId\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"4\n" +
	"\x13InitialAgentMessage\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"E\n" +
	"\x0eTerminalOutput\x12\x1f\n" +
	"\vterminal_id\x18\x01 \x01(\tR\n" +
	"terminalId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\":\n" +
	"\x17TerminalCreatedResponse\x12\x1f\n" +
	"\vterminal_id\x18\x01 \x01(\tR\n" +
	"terminalId\"\xd3\x01\n" +
	"\fServerUpdate\x12#\n" +
	"\fserver_hello\x18\x01 \x01(\tH\x00R\vserverHello\x127\n" +
	"\tpty_input\x18\x02 \x01(\v2\x18.shellsync.TerminalInputH\x00R\bptyInput\x12Z\n" +
	"\x17create_terminal_request\x18\x03 \x01(\v2 .shellsync.CreateTerminalRequestH\x00R\x15createTerminalRequestB\t\n" +
	"\apayload\"D\n" +
	"\rTerminalInput\x12\x1f\n" +
	"\vterminal_id\x18\x01 \x01(\tR\n" +
	"terminalId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"8\n" +
	"\x15CreateTerminalRequest\x12\x1f\n" +
	"\vterminal_id\x18\x01 \x01(\tR\n" +
	"terminalId2\x91\x01\n" +
	"\tShellSync\x12D\n" +
	"\rCreateSession\x12\x18.shellsync.CreateRequest\x1a\x19.shellsync.CreateResponse\x12>\n" +
	"\x06Stream\x12\x17.shellsync.ClientUpdate\x1a\x17.shellsync.ServerUpdate(\x010\x01B+Z)github.com/Ayush-Vish/shellsync/api/protob\x06proto3"

var (
	file_api_proto_shellsync_proto_rawDescOnce sync.Once
	file_api_proto_shellsync_proto_rawDescData []byte
)

func file_api_proto_shellsync_proto_rawDescGZIP() []byte {
	file_api_proto_shellsync_proto_rawDescOnce.Do(func() {
		file_api_proto_shellsync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_shellsync_proto_rawDesc), len(file_api_proto_shellsync_proto_rawDesc)))
	})
	return file_api_proto_shellsync_proto_rawDescData
}

var file_api_proto_shellsync_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_proto_shellsync_proto_goTypes = []any{
	(*CreateRequest)(nil),           // 0: shellsync.CreateRequest
	(*CreateResponse)(nil),          // 1: shellsync.CreateResponse
	(*ClientUpdate)(nil),            // 2: shellsync.ClientUpdate
	(*TerminalError)(nil),           // 3: shellsync.TerminalError
	(*InitialAgentMessage)(nil),     // 4: shellsync.InitialAgentMessage
	(*TerminalOutput)(nil),          // 5: shellsync.TerminalOutput
	(*TerminalCreatedResponse)(nil), // 6: shellsync.TerminalCreatedResponse
	(*ServerUpdate)(nil),            // 7: shellsync.ServerUpdate
	(*TerminalInput)(nil),           // 8: shellsync.TerminalInput
	(*CreateTerminalRequest)(nil),   // 9: shellsync.CreateTerminalRequest
}
var file_api_proto_shellsync_proto_depIdxs = []int32{
	4, // 0: shellsync.ClientUpdate.initial_message:type_name -> shellsync.InitialAgentMessage
	5, // 1: shellsync.ClientUpdate.pty_output:type_name -> shellsync.TerminalOutput
	6, // 2: shellsync.ClientUpdate.terminal_created_response:type_name -> shellsync.TerminalCreatedResponse
	3, // 3: shellsync.ClientUpdate.terminal_error:type_name -> shellsync.TerminalError
	8, // 4: shellsync.ServerUpdate.pty_input:type_name -> shellsync.TerminalInput
	9, // 5: shellsync.ServerUpdate.create_terminal_request:type_name -> shellsync.CreateTerminalRequest
	0, // 6: shellsync.ShellSync.CreateSession:input_type -> shellsync.CreateRequest
	2, // 7: shellsync.ShellSync.Stream:input_type -> shellsync.ClientUpdate
	1, // 8: shellsync.ShellSync.CreateSession:output_type -> shellsync.CreateResponse
	7, // 9: shellsync.ShellSync.Stream:output_type -> shellsync.ServerUpdate
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_api_proto_shellsync_proto_init() }
func file_api_proto_shellsync_proto_init() {
	if File_api_proto_shellsync_proto != nil {
		return
	}
	file_api_proto_shellsync_proto_msgTypes[2].OneofWrappers = []any{
		(*ClientUpdate_InitialMessage)(nil),
		(*ClientUpdate_PtyOutput)(nil),
		(*ClientUpdate_TerminalCreatedResponse)(nil),
		(*ClientUpdate_TerminalError)(nil),
	}
	file_api_proto_shellsync_proto_msgTypes[7].OneofWrappers = []any{
		(*ServerUpdate_ServerHello)(nil),
		(*ServerUpdate_PtyInput)(nil),
		(*ServerUpdate_CreateTerminalRequest)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_shellsync_proto_rawDesc), len(file_api_proto_shellsync_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_shellsync_proto_goTypes,
		DependencyIndexes: file_api_proto_shellsync_proto_depIdxs,
		MessageInfos:      file_api_proto_shellsync_proto_msgTypes,
	}.Build()
	File_api_proto_shellsync_proto = out.File
	file_api_proto_shellsync_proto_goTypes = nil
	file_api_proto_shellsync_proto_depIdxs = nil
}
